apiVersion: apps/v1
kind: Deployment
metadata:
  name: qna-transformers
spec:
  selector:
    matchLabels:
      app: qna-transformers
  replicas: 1
  template:
    metadata:
      labels:
        app: qna-transformers
    spec:
      containers:
        - name: qna-transformers
          image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
          stdin: true
          tty: true
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ENABLE_CUDA
              value: "0"
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: qna-transformers
spec:
  selector:
    app: qna-transformers
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
